name: ESP-IDF Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: espressif/idf:v5.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build example simple_tx
        run: |
          . /opt/esp/idf/export.sh
          cd example/simple_test/simple_tx
          idf.py set-target esp32
          idf.py build

      - name: Build example simple_rx
        run: |
          . /opt/esp/idf/export.sh
          cd example/simple_test/simple_rx
          idf.py set-target esp32
          idf.py build

      - name: Build example range_tx
        run: |
          . /opt/esp/idf/export.sh
          cd example/simple_test/range/range_tx
          idf.py set-target esp32
          idf.py build

      - name: Build example range_rx
        run: |
          . /opt/esp/idf/export.sh
          cd example/simple_test/range/range_rx
          idf.py set-target esp32
          idf.py build
